feat: change coveo key based on build environment
nginxinc/nginx-hugo-theme pull request #12
Opened 2023-06-08 15:28 UTC by Jcahilltorre

### Proposed changes

Logic added to create the coveo.js file with a different coveo key (prod and test) depending on the Hugo build environment.

Production uses the "production"  key
Staging uses the "staging"  key
Every other environment uses the "development" key

Tested locally, `-e production`  ` -e development` and  `-e staging` , developer console shows a different key in the minified coveo.js

### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [`CONTRIBUTING`](https://github.com/nginxinc/nginx-hugo-theme/blob/main/CONTRIBUTING.md) document
- [x] If applicable, I have added tests that prove my fix is effective or that my feature works
- [x] If applicable, I have checked that any relevant tests pass after adding my changes
- [x] I have updated any relevant documentation ([`README.md`](https://github.com/nginxinc/nginx-hugo-theme/blob/main/README.md) and [`CHANGELOG.md`](https://github.com/nginxinc/nginx-hugo-theme/blob/main/CHANGELOG.md))

2023-06-08 17:19 UTC, jputrino requested changes

2023-06-08 17:19 UTC, jputrino commented on layouts/partials/scripts.html
> +  {{ $.Scratch.Set "coveoSc" $coveo}}
There are 3 coveo environments -- test, staging, and production. Please add the staging API key here as an option as well.

2023-06-12 17:31 UTC, jputrino commented
The only reservation I have with this approach is that we would need to make any code change to 3 different files. Is there a less duplicative way to solve the problem?

2023-06-13 16:02 UTC, LukeBillington approved these changes

2023-06-13 16:03 UTC, jputrino approved these changes
Nice work! LGTM

2023-06-13 16:16 UTC, merged